# Generated by Django 4.1.2 on 2022-10-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_product', models.CharField(choices=[('V', 'variation'), ('S', 'simple')], default='V', max_length=1)),
                ('image_product', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/')),
            ],
        ),
    ]
