# Generated by Django 4.1.2 on 2022-11-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_product',
        ),
        migrations.AddField(
            model_name='product',
            name='descricao_curta',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='descricao_longa',
            field=models.TextField(default='produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produto_imagens/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='preco_marketing',
            field=models.FloatField(default=0, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promo.'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1),
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.FloatField()),
                ('preco_promocional', models.FloatField(default=0)),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
